#!/usr/bin/php
<?php
/*
    tools/distributionBuilder/ydocview
    YeAPF 0.8.48-54 built on 2016-04-08 16:28 (-3 DST)
    Copyright (C) 2004-2016 Esteban Daniel Dortta - dortta@yahoo.com
    2016-04-08 16:26:01 (-3 DST)
*/

  $mydir=dirname($_SERVER['SCRIPT_FILENAME']);
  $cmRequired=false;
  if (file_exists("$mydir/yclilib.php"))
    $cmLocation = "$mydir/yclilib.php";
  else
    $cmLocation = "$mydir/../yclilib.php";

  (@include_once "$cmLocation") or die("yclilib.php not found\n");

  $cwd=getcwd();
  $args = new ArgumentsProcessor(false);
  $myself=basename($argv[0]);
  $filename=$args->getSrc(0);

  echo "YeAPF 0.8.48 $myself\nCopyright (C) 2004-2016 Esteban Daniel Dortta - dortta@yahoo.com\n";
  if (($args->argValue('h;help')==true) || (trim($filename)=='')) {
    die("usage:\n\t$myself <filename>\tfilename is a .xdb created by ydocbuilder\n");
  }

  if (!function_exists("objet2array")) {
    function object2array($object) { return @json_decode(@json_encode($object),1); }
  }

  function showXdbInfo($margin, $xml, $type='file')
  {
    $ret="";
    if (isset($xml)) {
      $xml=object2array($xml);
      $marginStr=str_repeat(" ",$margin*2);
      foreach($xml as $info => $detail) {
        if ($type=='file') {
          if (isset($detail['folder']))
            $ret.=urldecode($marginStr."$info at ".$detail['folder']."\n");
        } else if ($type=='func') {
          if (!is_numeric($info)) {
            $ret.=urldecode($marginStr."function $info (");
            $pCount=0;
            if (isset($detail['parameters'])) {
              foreach($detail['parameters'] as $paramName=>$dummy) {
                if ($pCount++>0)
                  $ret.=", ";
                $ret.=$paramName;
              }
            }
            $ret.=")\n";
          }
        } else if ($type=='class') {
          if (!is_numeric($info)) {
            $ret.=urldecode($marginStr."class $info\n");
          }

        } else if ($type=='inner') {

        }
        $ret.=viewInside($margin, $detail);
      }
    }
    return $ret;
  }

  function viewInside($margin, $detail )
  {
    $ret="";
    $marginStr=str_repeat(" ",$margin*2);
    if (isset($detail['inner'])) {
      $ret.=showXdbInfo($margin+1, $detail['inner'],'inner');
    }
    if (isset($detail['classes'])) {
      $ret.=showXdbInfo($margin+1, $detail['classes'],'class');
    }
    if (isset($detail['functions'])) {
      $ret.=showXdbInfo($margin+1, $detail['functions'],'func');
    }
    return $ret;
  }

  if (file_exists($filename)) {
    $xml = simplexml_load_file($filename);
    echo showXdbInfo(0, $xml);
  } else
    die("\nfile '$filename' not found\n");
?>
