#!/bin/bash
# (C) 2017 Esteban D.Dortta
#
# tools/adb-release
# YeAPF 0.8.63-106 built on 2019-07-11 09:42 (-3 DST)
# Copyright (C) 2004-2019 Esteban Daniel Dortta - dortta@yahoo.com - MIT License
# 2018-07-09 14:58:27 (-3 DST)
#
# This set of scripts requires adb/android-sdk/cordova installed on your device.
# Has been well tested under Ubuntu 16 and MacOSX 10.11.6
# It is supposed to run on Cygwin

if [ -f www/js/version.js ]; then
  my_dir="$(dirname "$0")"
  source "$my_dir/adb-lib.inc.sh"

  sign="platforms/android/release-signing.properties"
  if [ ! -f "$sign" ];  then
    cp release-signing.properties $sign
  fi

  if [ -f "$sign" ]; then
    widget=`cat config.xml | grep id | grep widget | awk '{print $2}' | awk -F\= '{print $2}'`
    widget=`eval echo $widget`

    versao="$(currentVersion)"

    echo Compiling $versao

    tgt="../../PlayStore/$widget-$versao.apk"

    cordova build android --release && \
    cp platforms/android/build/outputs/apk/android-release.apk $tgt
    echo Ready:
    echo $tgt
  else
    echo "Was not possible to compile"
  fi
else
  echo "www/js/version.js file not found"
fi