#!/bin/bash
# (C) 2018 Esteban D.Dortta
#
# tools/adb-photo
# YeAPF 0.8.61-12 built on 2018-07-09 16:23 (-3 DST)
# Copyright (C) 2004-2018 Esteban Daniel Dortta - dortta@yahoo.com
# 2018-07-09 14:58:28 (-3 DST)
#
# This set of scripts requires adb/android-sdk/cordova installed on your device.
# Has been well tested under Ubuntu 16 and MacOSX 10.11.6
# It is supposed to run on Cygwin

if [ -f www/js/version.js ]; then
	mkdir -p devicePhotos
	d=`date +%Y%m%d%H%M%S`
	adb shell screencap -p | perl -pe 's/\x0D\x0A/\x0A/g' > devicePhotos/screen-$d.png
else
	echo "www/js/version.js file not found"
fi