#!/bin/bash
# (C) 2016 Esteban D.Dortta
#
# tools/adb-debug
# YeAPF 0.8.61-3 built on 2018-07-09 15:12 (-3 DST)
# Copyright (C) 2004-2018 Esteban Daniel Dortta - dortta@yahoo.com
# 2018-07-09 14:58:38 (-3 DST)
#
# This set of scripts requires adb/android-sdk/cordova installed on your device.
# Has been well tested under Ubuntu 16 and MacOSX 10.11.6
# It is supposed to run on Cygwin

if [ -f www/js/version.js ]; then
	my_dir="$(dirname "$0")"
	source "$my_dir/adb-lib.inc.sh"

	version="$(currentVersion)"

	dev=$1
	if [ -z $dev ]; then
	  dev=$firstdev
	fi

	if [ $devcount -eq 0 ]; then
	  echo "Please, attach/indicate a device"
	else
	  echo "device=$dev"

	  w="$(widgetName)"
	  adb -s $dev logcat | grep `adb -s $dev shell ps | grep -i $w | cut -c10-15`
	fi
else
	echo "www/js/version.js file not found"
fi