#!/usr/bin/php
<?php
  /*
   * tools
   * tools/ycreatewebappevent
   * YeAPF 0.8.50-10 built on 2016-08-29 09:16 (-3 DST)
   * Copyright (C) 2004-2016 Esteban Daniel Dortta - dortta@yahoo.com
   * 2016-03-17 11:18:47 (-3 DST)
   */

  $mydir=dirname($_SERVER['SCRIPT_FILENAME']);
  $cmRequired=false;
  (@include_once "$mydir/yclilib.php") or die("yclilib.php not found\n");

  $args = new ArgumentsProcessor();
  $eventName=$args->getSrc(0);
  $appFolder=$args->getSrc(1);
  $toHelp=$args->argValue('help',__FALSE__)==__TRUE__;

  if ($appFolder=='')
    $appFolder='./';

  echo "ycreatewebappevent\nYeAPF 0.8.50\n";
  if (($toHelp) || ($eventName=='')) {
    echo "simple usage:\n\t".basename("tools/ycreatewebappevent")." <subject> [app-folder]\n\n";
    echo "\t app-folder defaults to current working directory\n";
    die("\n\n");
  }

  if (!is_dir($appFolder))
    die("'$appFolder' is not a folder");

  if ($eventName=='') {
    echo "You need tell the event verb map\n";
  } else {
    if (is_dir($appFolder)) {
      if (file_exists("$appFolder/yeapf.php")) {
        echo "YeAPF folder: $__yeapfPath\n";
        if (file_exists("$appFolder/slotEmptyImplementation.php"))
          $sei_filename="$appFolder/slotEmptyImplementation.php";
        else
          $sei_filename="$__yeapfPath/skel/webApp/slotEmptyImplementation.php";

        if (!file_exists($sei_filename))
          die("Error: $sei_filename not found!");


        $yeapfConfigLoaded=false;
        if (file_exists("$appFolder/.config/yeapf.config")) {
          (@include_once("$appFolder/.config/yeapf.config")) || die("Erro ao carregar yeapf.config");
          $yeapfConfigLoaded=true;
        }
        if (!$yeapfConfigLoaded) {
          $yeapfConfig=array();
          $yeapfConfig['yeapfDB']="$appFolder/sgug.ini";
        }
        if (isset($yeapfConfig['yeapfDB'])) {
          echo "dbConfig = ".$yeapfConfig['yeapfDB']."\nLoading .";
          $dbConnect='no';
          $cfgCLI=true;
          _LOAD_YEAPF_();
          echo "..\n";
          $eventManager="$appFolder/$eventName.php";
          $eventManager=str_replace("//", "/", $eventManager);
          if (!file_exists($eventManager)) {
            echo "Creating event manager '$eventManager'\n";
            $GLOBALS['s']=$eventName;
            $newEventScript=_file($sei_filename);
            $f=fopen($eventManager, "w");
            fwrite($f,$newEventScript);
            fclose($f);
          } else
            echo "Event manager '$eventManager' untouched\n";
        } else
          die("Error: db connection cannot be found.\nCreate yeapf.db.ini and run configure.php again\n");


      } else
        die ("Error: '$appFolder' is not well configured.\nRun 'configure.php' from your browser first\n\n");
    } else
      die("$appFolder is not a folder\n");

  }
?>
