#!/usr/bin/php
<?php
  /*
   * cloudManager
   * cloudManager
   * tools/cloudManager/cmscp
   * YeAPF 0.8.60-67 built on 2018-05-30 11:21 (-3 DST)
   * Copyright (C) 2004-2018 Esteban Daniel Dortta - dortta@yahoo.com
   * 2018-05-30 11:21:05 (-3 DST)
   *
   * purpouse: to copy file over the network.
   */

  (@include_once "yclilib.php") or die("yclilib.php not found\n");
  if ($argc==3) {

    doOnCloud('scp');

  } else {
    $myself=$argv[0];
    echo "$myself src dest\n";
    echo "src or dest can be node referenced as in these samples:\n";
    echo "  $myself *.html A:/var/www/html    (copy all html files to the 'A' node)\n";
    echo "  $myself *.php *:/var/www/html   (copy all php files to all nodes)\n";
    echo "\n\nWARNING: Disable bash wildcard expansion with 'set -f' statement before use this command";
  }
?>
