#!/usr/bin/php
<?php
  /*
   * tools
   * tools/yupdate
   * YeAPF 0.8.64-7 built on 2020-03-20 13:04 (-3 DST)
   * Copyright (C) 2004-2020 Esteban Daniel Dortta - dortta@yahoo.com - MIT License
   * 2019-06-06 08:35:20 (-3 DST)
   */

  echo basename("tools/yupdate") . "\nYeAPF 0.8.64 tools\nCopyright (C) 2004-2020 Esteban Daniel Dortta - dortta@yahoo.com - MIT License\n\n";
  echo "WARNING: This has become obsolete.\nPlease use yapp instead\n";
?>
