#!/bin/bash
# (C) 2017 Esteban D.Dortta
#
# tools/adb-release
# YeAPF 0.8.60-119 built on 2018-06-08 05:44 (-3 DST)
# Copyright (C) 2004-2018 Esteban Daniel Dortta - dortta@yahoo.com
# 2018-06-01 09:31:47 (-3 DST)

if [ -f www/js/version.js ]; then
  my_dir="$(dirname "$0")"
  source "$my_dir/adb-lib.inc.sh"

  sign="platforms/android/release-signing.properties"
  if [ ! -f "$sign" ];  then
    cp release-signing.properties $sign
  fi

  if [ -f "$sign" ]; then
    widget=`cat config.xml | grep id | grep widget | awk '{print $2}' | awk -F\= '{print $2}'`
    widget=`eval echo $widget`

    versao="$(currentVersion)"

    echo Compiling $versao

    tgt="../../PlayStore/$widget-$versao.apk"

    cordova build android --release && \
    cp platforms/android/build/outputs/apk/android-release.apk $tgt
    echo Ready:
    echo $tgt
  else
    echo "Was not possible to compile"
  fi
else
  echo "www/js/version.js file not found"
fi