#!/bin/bash
# (C) 2018 Esteban D.Dortta
#
# tools/adb-photo
# YeAPF 0.8.60-119 built on 2018-06-08 05:44 (-3 DST)
# Copyright (C) 2004-2018 Esteban Daniel Dortta - dortta@yahoo.com
# 2018-06-01 09:31:47 (-3 DST)

if [ -f www/js/version.js ]; then
	mkdir -p devicePhotos
	d=`date +%Y%m%d%H%M%S`
	adb shell screencap -p | perl -pe 's/\x0D\x0A/\x0A/g' > devicePhotos/screen-$d.png
else
	echo "www/js/version.js file not found"
fi